version: 1
disable_existing_loggers: False

formatters:
    simple_formatter:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
    console_handler:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple_formatter
        stream: ext://sys.stdout

    file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple_formatter
        filename: /Users/jon/tmp/dex.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

loggers:
    dex:
        level: DEBUG
        handlers: [file_handler]
        propagate: no

root:
    level: DEBUG
    handlers: [file_handler]